services:
  app:
    build:
      context: ./investorhub-services
      dockerfile: Dockerfile
    container_name: nestjs_app_investorhub
    ports:
      - "3000:3000"
    depends_on:
      redis_investorhub:
        condition: service_healthy
      mongodb_investorhub:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./.env:/app/.env
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=3000"
      - "prometheus.path=/metrics"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  clock:
    build:
      context: ./investorhub-clock
      dockerfile: Dockerfile
    container_name: nestjs_app_investorhub_clock
    ports:
      - "3001:3000"
    depends_on:
      redis_investorhub:
        condition: service_healthy
      mongodb_investorhub:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./.env:/app/.env
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=3000"
      - "prometheus.path=/metrics"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb_investorhub:
    image: mongo:4.2.12-bionic
    container_name: mongodb_investorhub
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin123}
    volumes:
      - mongodb_data_investorhub:/data/db
    command: mongod --bind_ip_all
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"

  redis_investorhub:
    image: redis:7
    container_name: redis_server_investorhub
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data_investorhub:/data
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana_investorhub:
    image: grafana/grafana:latest
    container_name: grafana_investorhub
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data_investorhub:/var/lib/grafana
    depends_on:
      - prometheus_investorhub
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"

  prometheus_investorhub:
    image: prom/prometheus:latest
    container_name: prometheus_investorhub
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data_investorhub:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: unless-stopped

  node-exporter_investorhub:
    image: prom/node-exporter:latest
    container_name: node-exporter_investorhub
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped

volumes:
  mongodb_data_investorhub:
  redis_data_investorhub:
  grafana_data_investorhub:
  prometheus_data_investorhub:
